### ISSUE TITLE
Error building Godot with this module on Linux

### ISSUE THREAD

**Issue by ShawkMusic** [nathanfranke/gdaudioyt#1]
```scons: Reading SConscript files ...

scons: *** Illegal Variables key `module_gdaudioyt-main_enabled'
File "~/Downloads/openplayer/godot-3.x/SConstruct", line 292, in <module>
```

I was following the instructions on compiling at https://github.com/nathanfranke/open-player/
I added this module to the 'modules' folder on the Godot source code, added the custom.py file to the godot-3.x/ folder, and then ran `scons -j8 platform=x11` and got that error

I have never compiled Godot from source before btw

**Comment by nathanfranke** [comment]
Can you clean clone Godot 3.x, then clone gdaudioyt in modules? Now run scons and show me the full output? I can take a look at this in an hour.

**Comment by ShawkMusic** [comment]
>Edit: you shouldn't need to copy the custom.py file anywhere.
Then what do I do with it? Should I just delete it?

>P.S: there are prebuilt binaries available for OpenPlayer already, in case you didn't know. But compiling is also useful.
I know, I want to modify it in Godot engine

**Comment by ShawkMusic** [comment]
>Can you clean clone Godot 3.x, then clone gdaudioyt in modules? Now run scons and show me the full output. I can take a look at this in an hour.

I did this and now it seems to be compiling fine. I'll keep this thread updated.

I think it might've been the custom.py file that was messing it up. Idk tho

**Comment by nathanfranke** [comment]
I don't have custom.py on my copy of Godot 3.x, so you can safely delete it. That was likely messing up the build.

**Comment by nathanfranke** [comment]
If you have further issues, let me know so I can re-open the issue. But thanks for checking out my projects and good luck with what you're doing!

**Comment by ShawkMusic** [comment]
Yes, it looked like it worked now. Thanks for the help!

I had an issue with OpenPlayer but i'll put that on it's repo
